FundDesSoftware168-2020-1/Codifica-Decodifica-String

- Codificadores/Codifica151051836.java
Codificador que adiciona "guampinhas"
> Adicionado codificador 15105183-6

- Codificadores/Codifica172120149.java
Codifica a string substituindo cada caracter para seu valor hexadecimal correspondente em ASCII.
> Adiciona um novo codificador chamado Codifica172120149

- Codificadores/Codifica18108174.java
Ao codificar a mensagem, ele verifica se a mensagem tem até 10 caracteres, se tiver, faz a movimentação de letras referente ao que a mesma tiver de caracteres.
Caso não tenha, divide por dois até se encaixar no padrão.
A cada 2 caracteres adicionados ou removidos (em relação a quantidade), o número é diferente
> Codifica18108174

- Codificadores/Codifica11109498.java
PR referente ao exercício de implementação de algoritmo de criptografia/descriptografia.
> Adição da classe Codifica11109498 por Priscilla Karolczak

- Codificadores/Codifica161111786.java
Codificação da classe Codifica161111786.
> Criacao da classe Codifica161111786

- Codificadores/Codifica191052778.java
Codificador substitui vogais da String por caracteres especiais.
> Adiciona classe 191052778

- Codificadores/Codifica12104893.java
Added student 12104893 Coding/Encoding class on 23-02-2020 17:18
> Added student 12104893 Coding/Encoding class

- Codificadores/Codifica18106112.java
Corrigido o antigo erro, não havia sido feito o add por isso não vinha o código.
> Bruno abbad

- Codificadores/Codifica15109536.java
ola, fiz uma modificações extraordinárias no decodificador, não recomendo ficar sem =]
> pasta bin adicionada, meu decodificador implementado

- Codificadores/Codifica19180149.java
Adiciona o codificador 19180149 que transforma cada char da string em seu respectivo valor inteiro
> Adiciona Codificador 19180149

- Codificadores/Codifica20181044.java
Professor, criei uma classe para codificação de String onde grava na posição zero o valor da chave (int aleatório entre 4 e 7).
Não ficou claro pra mim se a impressão da String codificada deve ser "amigável" ou legível, pois em outros testes, manipulando os valores de "char", causou impressões de caracteres que bagunçam a formatação de saída no print. Desta forma, preferi limitar a chave para valores próximos, que não alcançariam caracteres especiais "char" que tornassem a impressão ilegível.
Aguardo suas considerações. De todo modo, a classe está funcional.
> Adicionada classe correspondente a minha matrícula

- Codificadores/Codifica181105495.java
Aluna: Daniela Pereira Rigoli
Turma 168
Adicionada a classe codifica 181105495.
> codifica 181105495

- Codificadores/Codifica17111131.java
Codificador que soma um valor Inteiro a cada caractere da string. Este valor é baseado em uma chave de String.
> Adicionando Codificado 17111131

- Codificadores/Codifica201011350.java
O codificador aplica 4 passos de codificação, que estão descritos em forma de comentário na classe Codifica201011350.
> Adicionado codificador 201011350

- App.java
- Codificadores/Codifica172022113.java
- Codificadores/Codifica20101204.java
> Codificador feito 20101204 

- Codificadores/Codifica20106788.java
Codificador que, para vogais, "pula" uma letra e para consoantes, três letras. 
Para números multiplica por 13 e coloca o resultado entre hífens.
> adicionado codificador 20106788

- Codificadores/Codifica201034287.java
As vogais foram trocadas por caracteres especiais.
> Adicionado 201034287

- Codificadores/Codifica17120081.java
Codificador adicionado poucas mudanças.
> Adiciionado codificador 17120081

- Codificadores/Codifica19280020.java
Codificador que troca vogais por números e inverte a frase/palavra
> Adicionado  Codifica19280020

- App.java
- Codificadores/Codifica2010.java
OLáprofessor venho aqui novamente solicitar por obséquio a aceitação do meu pull request
> Codifica20102488

- Codificadores/Codifica20102813.java
Aceita meu pull request sor!! :))))
> codifica20102813 adicionado(fernanda)

- Codificadores/Codifica14108828.java
Novo codificador 14108828 - Ísis Vargas
> Codificador 14108828

- Codificadores/Codifica181061938.java
> Adicionado codificador 181061938

- Codificadores/Codifica20280524.java
Implementei o codificador para a minha matrícula: 20280524
> Codificador com nome e matricula pessoais

- Codificadores/Codifica20200311.java
Estou submetendo a criação da classe Codifica20200311.java como contribuição para o projeto.
> classe codifica20200311

- Codificadores/Codifica20204012.java
Trabalho 2 criação de pull request
Nome: Cassiano Luis Flores Michel
Matrícula: 20204012
> nova-classe-codifica20204012

- Codificadores/Codifica20204015.java
Colaborando em projetos de código aberto
T2: Pull Request
20204015 Mateus Carvalho
> Colaborando em projetos de código aberto

- Codificadores/Codifica1119.java
Eduardo Cardoso 20101119-4
Adiciona uma letra incomum nas linguagens estrangeiras.
> mensagem codificada e decodificada.

- Codificadores/Codifica17204096.java
> Created Codifica17204096.java

- Codificadores/Codifica16204151.java
> Adicionado codificador 16204051

- Codificadores/Codifica211021381.java
Autor: Gabriel dos Passos Ramos
Matrícula: 1102138-1
Codificação: Inverter String
> Create class Codifica211021381

- Codificadores/CodificaAnderson.java
Criação da Classe CodificaAnderson.Java
> Adicionado Pull Request 14201795-3

- Codificadores/Codifica10102704.java
> Adicionado codificador 10102704
